import { useEffect, useState } from 'react';
import { Download, RefreshCw } from 'lucide-react';
import { api, SalesRow } from '../api';

export function ReportsWorkspace() {
  const [catalog, setCatalog] = useState<SalesRow[]>([]); const [selected, setSelected] = useState(''); const [status, setStatus] = useState(''); const [project, setProject] = useState(''); const [rows, setRows] = useState<SalesRow[]>([]); const [total, setTotal] = useState(0); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const load = async () => { if (!selected) return; setBusy(true); setError(''); try { const result = await api.reportData(selected, { status, project, page: 0, size: 100 }); setRows(result.rows); setTotal(result.rowCount); } catch (err) { setError(err instanceof Error ? err.message : 'Report could not be loaded.'); } finally { setBusy(false); } };
  useEffect(() => { api.reportCatalog().then(items => { setCatalog(items); if (items[0]?.key) setSelected(String(items[0].key)); }).catch(err => setError(err instanceof Error ? err.message : 'Report catalogue could not be loaded.')); }, []);
  useEffect(() => { load(); }, [selected]);
  const exportReport = async (format: 'csv' | 'excel' | 'pdf') => { try { const blob = await api.reportExport(selected, format, { status, project }); const anchor = document.createElement('a'); anchor.href = URL.createObjectURL(blob); anchor.download = `${selected}.${format === 'excel' ? 'xls' : format}`; anchor.click(); } catch (err) { setError(err instanceof Error ? err.message : 'Report export failed.'); } };
  const columns = rows.length ? Object.keys(rows[0]) : [];
  return <div className="page"><div className="page-top"><div><p className="eyebrow">REPORTING & INSIGHTS</p><h2>Operational reports</h2><p className="muted">Role-scoped reports with server-side filtering, row counts, audit-backed exports, and empty states.</p></div><div className="page-actions"><button className="secondary" onClick={() => exportReport('csv')} disabled={!selected}><Download size={16}/>CSV</button><button className="secondary" onClick={() => exportReport('excel')} disabled={!selected}>Excel</button><button className="primary" onClick={() => exportReport('pdf')} disabled={!selected}>PDF</button></div></div>{error && <p className="error">{error}</p>}<section className="card recent"><div className="filters"><label className="inline-label">Report<select className="filter" value={selected} onChange={event => setSelected(event.target.value)}>{catalog.map(item => <option key={String(item.key)} value={String(item.key)}>{String(item.name)}</option>)}</select></label><label className="inline-label">Status<input className="filter" value={status} onChange={event => setStatus(event.target.value)} placeholder="Optional" /></label><label className="inline-label">Project<input className="filter" value={project} onChange={event => setProject(event.target.value)} placeholder="Optional" /></label><button className="secondary" onClick={load} disabled={busy}><RefreshCw size={15}/>Apply</button><span className="count">{busy ? 'SYNCING' : `${total} ROWS`}</span></div></section><section className="card recent"><div className="card-head"><div><p className="eyebrow">LIVE REPORT</p><h3>{String(catalog.find(item => String(item.key) === selected)?.name || 'Select a report')}</h3></div></div>{rows.length ? <div className="table-wrap"><table><thead><tr>{columns.map(column => <th key={column}>{column.replaceAll('_', ' ')}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{columns.map(column => <td key={column}>{String(row[column] ?? '-').replaceAll('_', ' ')}</td>)}</tr>)}</tbody></table></div> : <p className="empty">No rows match the selected report filters.</p>}</section></div>;
}
