import { useEffect, useMemo, useState } from 'react';
import { Download, RefreshCw } from 'lucide-react';
import { api, SalesRow } from '../api';

const read = (row: Record<string, unknown>, key: string) => row[key] ?? row[Object.keys(row).find(candidate => candidate.toLowerCase() === key.toLowerCase()) || key] ?? '-';
const ticketStatuses = ['OPEN', 'ASSIGNED', 'IN_PROGRESS', 'WAITING_CUSTOMER', 'RESOLVED', 'CLOSED'];
const maintenanceStatuses = ['SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'];

export function SupportOperationsWorkspace({ module }: { module: string }) {
  const [dashboard, setDashboard] = useState<Record<string, unknown> | null>(null); const [rows, setRows] = useState<SalesRow[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const load = async () => { setBusy(true); setError(''); try { setDashboard(await api.supportDashboard()); setRows(module === 'Complaints' || module === 'Customers' ? await api.supportTickets() : await api.supportMaintenance()); } catch (err) { setError(err instanceof Error ? err.message : 'Support workspace could not be loaded.'); } finally { setBusy(false); } };
  useEffect(() => { load(); }, [module]);
  const update = async (row: SalesRow, status: string) => { setBusy(true); setError(''); try { if (module === 'Maintenance') await api.updateMaintenanceStatus(String(read(row, 'id')), { status }); else await api.updateSupportStatus(String(read(row, 'id')), { status }); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Status update failed.'); setBusy(false); } };
  const comment = async (row: SalesRow) => { const text = window.prompt('Add a support note'); if (!text) return; setBusy(true); try { await api.addSupportComment(String(read(row, 'id')), text); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Comment could not be added.'); setBusy(false); } };
  const columns = useMemo(() => rows.length ? Object.keys(rows[0]) : [], [rows]);
  const exportRows = () => { if (!rows.length) return; const csv = [columns, ...rows.map(row => columns.map(column => String(row[column] ?? '').replaceAll('"', '""')))].map(row => row.map(cell => `"${cell}"`).join(',')).join('\n'); const anchor = document.createElement('a'); anchor.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); anchor.download = `support-${module.toLowerCase()}.csv`; anchor.click(); };
  const tickets = module !== 'Maintenance';
  return <div className="page"><div className="page-top"><div><p className="eyebrow">CUSTOMER EXPERIENCE</p><h2>{module}</h2><p className="muted">SLA-aware support operations with controlled ticket, maintenance, and customer follow-up status updates.</p></div><div className="page-actions"><button className="secondary" onClick={exportRows}><Download size={16}/>Export</button><button className="secondary" onClick={load} disabled={busy}><RefreshCw size={16}/>Refresh</button></div></div>{error && <p className="error">{error}</p>}{dashboard && <section className="stat-grid"><article className="stat-card coral"><p>Open complaints</p><h3>{String(read(dashboard, 'openComplaints'))}</h3><span>Customer issues</span></article><article className="stat-card blue"><p>Service requests</p><h3>{String(read(dashboard, 'serviceRequests'))}</h3><span>Active queue</span></article><article className="stat-card gold"><p>SLA breaches</p><h3>{String(read(dashboard, 'slaBreaches'))}</h3><span>Escalation required</span></article><article className="stat-card"><p>Maintenance scheduled</p><h3>{String(read(dashboard, 'maintenanceScheduled'))}</h3><span>Upcoming visits</span></article></section>}<section className="card recent"><div className="card-head"><div><p className="eyebrow">LIVE SUPPORT DATA</p><h3>{rows.length} records</h3></div><span className="count">{busy ? 'SYNCING' : 'CONNECTED'}</span></div>{rows.length ? <div className="table-wrap"><table><thead><tr>{columns.map(column => <th key={column}>{column.replaceAll('_', ' ')}</th>)}<th>Actions</th></tr></thead><tbody>{rows.map(row => { const status = String(read(row, 'status')); const options = tickets ? ticketStatuses : maintenanceStatuses; return <tr key={String(read(row, 'id'))}>{columns.map(column => <td key={column}>{String(read(row, column)).replaceAll('_', ' ')}</td>)}<td><select className="filter" value={status} onChange={event => update(row, event.target.value)} disabled={busy}>{options.map(option => <option key={option}>{option}</option>)}</select>{tickets && <button className="text-button" onClick={() => comment(row)} disabled={busy}>Add note</button>}</td></tr>; })}</tbody></table></div> : <p className="empty">No support records available.</p>}</section></div>;
}
