package com.saivandan.crm.sales;

import com.saivandan.crm.security.AuditService;
import com.saivandan.crm.security.CurrentUser;
import com.saivandan.crm.user.RoleCode;
import jakarta.transaction.Transactional;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;
import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.*;

@RestController
@RequestMapping("/sales")
public class SalesLifecycleController {
  private final JdbcTemplate jdbc; private final AuditService audit;
  public SalesLifecycleController(JdbcTemplate jdbc, AuditService audit){this.jdbc=jdbc;this.audit=audit;}

  @GetMapping("/executives") @PreAuthorize("hasAnyRole('SUPER_ADMIN','SALES_MANAGER','SALES_EXECUTIVE')")
  public List<Map<String,Object>> executives(){
    return jdbc.queryForList("select u.id,u.full_name as fullName,u.email from users u join user_roles ur on ur.user_id=u.id join roles r on r.id=ur.role_id where u.active=true and r.code='SALES_EXECUTIVE' order by u.full_name");
  }

  @GetMapping("/leads/{leadId}/qualification") @PreAuthorize("hasAnyRole('SUPER_ADMIN','SALES_MANAGER','SALES_EXECUTIVE')")
  public Map<String,Object> qualification(@PathVariable UUID leadId,@AuthenticationPrincipal CurrentUser current){return leadView(current,leadId);}

  @PatchMapping("/leads/{leadId}/qualification") @PreAuthorize("hasAnyRole('SUPER_ADMIN','SALES_MANAGER','SALES_EXECUTIVE')")
  public Map<String,Object> qualify(@PathVariable UUID leadId,@Valid @RequestBody QualificationRequest req,@AuthenticationPrincipal CurrentUser current){
    Map<String,Object> before=leadView(current,leadId); int score=score(req); String temperature=score>=70?"HOT":score>=40?"WARM":"COLD";
    jdbc.update("update leads set budget_min=?,budget_max=?,loan_required=?,preferred_location=?,preferred_configuration=?,purchase_timeline=?,purchase_purpose=?,notes=?,qualification_score=?,temperature=?,updated_at=current_timestamp where id=?",req.budgetMin(),req.budgetMax(),req.loanRequired(),req.preferredLocation(),req.configuration(),req.purchaseTimeline(),req.purchasePurpose(),req.notes(),score,temperature,leadId);
    if("NEW".equals(String.valueOf(before.get("status")))) jdbc.update("update leads set status='QUALIFIED' where id=?",leadId);
    audit.record(current.user().getId(),"LEAD",leadId,"QUALIFY",before.toString(),"score="+score+",temperature="+temperature,null); return leadView(current,leadId);
  }

  @GetMapping("/leads/duplicate-check") @PreAuthorize("hasAnyRole('SUPER_ADMIN','SALES_MANAGER','SALES_EXECUTIVE')")
  public List<Map<String,Object>> duplicateCheck(@RequestParam String mobile,@RequestParam(required=false) String email,@RequestParam(required=false) String name){
    return jdbc.queryForList("select id,lead_number as leadNumber,customer_name as customer,mobile,email,status from leads where deleted_at is null and (mobile=? or (? is not null and lower(email)=lower(?)) or (? is not null and lower(customer_name)=lower(?))) order by created_at desc",mobile,email,email,name,name);
  }

  @PostMapping("/leads/{leadId}/transfer") @PreAuthorize("hasAnyRole('SUPER_ADMIN','SALES_MANAGER')")
  @Transactional
  public Map<String,Object> transfer(@PathVariable UUID leadId,@Valid @RequestBody TransferRequest req,@AuthenticationPrincipal CurrentUser current){
    Map<String,Object> before=leadView(current,leadId); UUID oldId=uuid(before.get("assignedTo")); Integer exists=jdbc.queryForObject("select count(*) from users u join user_roles ur on ur.user_id=u.id join roles r on r.id=ur.role_id where u.id=? and u.active=true and r.code='SALES_EXECUTIVE'",Integer.class,req.assigneeId()); if(exists==null||exists==0)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Lead can only be transferred to an active Sales Executive.");
    jdbc.update("update leads set assigned_to=?,updated_at=current_timestamp where id=?",req.assigneeId(),leadId); jdbc.update("insert into lead_assignment_history(lead_id,from_user_id,to_user_id,reason,changed_by) values (?,?,?,?,?)",leadId,oldId,req.assigneeId(),req.reason(),current.user().getId()); audit.record(current.user().getId(),"LEAD",leadId,"TRANSFER",before.toString(),req.assigneeId().toString(),null); return leadView(current,leadId);
  }

  @GetMapping("/leads/{leadId}/timeline") @PreAuthorize("hasAnyRole('SUPER_ADMIN','SALES_MANAGER','SALES_EXECUTIVE')")
  public Map<String,Object> timeline(@PathVariable UUID leadId,@AuthenticationPrincipal CurrentUser current){leadView(current,leadId); return Map.of("activities",jdbc.queryForList("select id,type,outcome,remarks,scheduled_at as scheduledAt,completed_at as completedAt,next_follow_up_at as nextFollowUpAt,call_duration_seconds as callDurationSeconds,customer_response as customerResponse,created_at as createdAt from lead_activities where lead_id=? order by created_at desc",leadId),"assignments",jdbc.queryForList("select h.created_at as createdAt,fu.full_name as fromUser,tu.full_name as toUser,h.reason from lead_assignment_history h left join users fu on fu.id=h.from_user_id left join users tu on tu.id=h.to_user_id where h.lead_id=? order by h.created_at desc",leadId));}

  @PostMapping("/leads/{leadId}/follow-ups") @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAnyRole('SUPER_ADMIN','SALES_MANAGER','SALES_EXECUTIVE')")
  public Map<String,Object> followUp(@PathVariable UUID leadId,@Valid @RequestBody FollowUpRequest req,@AuthenticationPrincipal CurrentUser current){leadView(current,leadId); UUID id=UUID.randomUUID(); jdbc.update("insert into lead_activities(id,lead_id,type,outcome,remarks,scheduled_at,next_follow_up_at,call_duration_seconds,customer_response,created_by) values (?,?,?,?,?,?,?,?,?,?)",id,leadId,req.type(),req.outcome(),req.remarks(),req.scheduledAt(),req.nextFollowUpAt(),req.callDurationSeconds(),req.customerResponse(),current.user().getId()); audit.record(current.user().getId(),"LEAD_ACTIVITY",id,"CREATE",null,req.type(),null); return jdbc.queryForMap("select id,type,outcome,remarks,scheduled_at as scheduledAt,next_follow_up_at as nextFollowUpAt,call_duration_seconds as callDurationSeconds,customer_response as customerResponse,created_at as createdAt from lead_activities where id=?",id);}

  @GetMapping("/follow-ups") @PreAuthorize("hasAnyRole('SUPER_ADMIN','SALES_MANAGER','SALES_EXECUTIVE')")
  public List<Map<String,Object>> followUps(@AuthenticationPrincipal CurrentUser current,@RequestParam(defaultValue="false") boolean overdue){String condition=overdue?" and a.next_follow_up_at<current_timestamp":""; if(isExecutive(current)) return jdbc.queryForList("select a.id,l.lead_number as leadNumber,l.customer_name as customer,a.type,a.remarks,a.next_follow_up_at as nextFollowUpAt,a.created_at as createdAt from lead_activities a join leads l on l.id=a.lead_id where l.assigned_to=? and a.next_follow_up_at is not null"+condition+" order by a.next_follow_up_at",current.user().getId()); return jdbc.queryForList("select a.id,l.lead_number as leadNumber,l.customer_name as customer,a.type,a.remarks,a.next_follow_up_at as nextFollowUpAt,a.created_at as createdAt,u.full_name as executive from lead_activities a join leads l on l.id=a.lead_id left join users u on u.id=l.assigned_to where a.next_follow_up_at is not null"+condition+" order by a.next_follow_up_at");}

  @PostMapping("/leads/{leadId}/site-visits") @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAnyRole('SUPER_ADMIN','SALES_MANAGER','SALES_EXECUTIVE')")
  public Map<String,Object> siteVisit(@PathVariable UUID leadId,@Valid @RequestBody SiteVisitRequest req,@AuthenticationPrincipal CurrentUser current){leadView(current,leadId); UUID executiveId=isExecutive(current)?current.user().getId():req.executiveId(); if(executiveId==null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"An executive is required for the site visit."); UUID id=UUID.randomUUID(); jdbc.update("insert into site_visits(id,lead_id,visit_date,visit_time,executive_id,status,pickup_required,pickup_address,visitor_count,preferred_unit_id,feedback,rating,objections,next_action) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)",id,leadId,req.date(),req.time(),executiveId,"SCHEDULED",Boolean.TRUE.equals(req.pickupRequired()),req.pickupAddress(),req.visitorCount()==null?1:req.visitorCount(),req.preferredUnitId(),req.feedback(),req.rating(),req.objections(),req.nextAction()); jdbc.update("update leads set status='SITE_VISIT_SCHEDULED' where id=? and status in ('NEW','QUALIFIED','CONTACTED')",leadId); audit.record(current.user().getId(),"SITE_VISIT",id,"CREATE",null,req.date().toString(),null); return jdbc.queryForMap("select id,lead_id as leadId,visit_date as date,visit_time as time,executive_id as executiveId,status,pickup_required as pickupRequired,pickup_address as pickupAddress,visitor_count as visitorCount,preferred_unit_id as preferredUnitId,feedback,rating,objections,next_action as nextAction from site_visits where id=?",id);}

  @GetMapping("/site-visits") @PreAuthorize("hasAnyRole('SUPER_ADMIN','SALES_MANAGER','SALES_EXECUTIVE')")
  public List<Map<String,Object>> siteVisits(@AuthenticationPrincipal CurrentUser current){if(isExecutive(current))return jdbc.queryForList("select s.id,l.lead_number as leadNumber,l.customer_name as customer,s.visit_date as date,s.visit_time as time,s.status,s.pickup_required as pickupRequired,s.feedback,s.rating,s.next_action as nextAction from site_visits s join leads l on l.id=s.lead_id where s.executive_id=? order by s.visit_date desc",current.user().getId()); return jdbc.queryForList("select s.id,l.lead_number as leadNumber,l.customer_name as customer,s.visit_date as date,s.visit_time as time,s.status,s.pickup_required as pickupRequired,s.feedback,s.rating,s.next_action as nextAction,u.full_name as executive from site_visits s join leads l on l.id=s.lead_id left join users u on u.id=s.executive_id order by s.visit_date desc");}

  @PatchMapping("/site-visits/{visitId}") @PreAuthorize("hasAnyRole('SUPER_ADMIN','SALES_MANAGER','SALES_EXECUTIVE')")
  public Map<String,Object> updateVisit(@PathVariable UUID visitId,@Valid @RequestBody VisitUpdateRequest req,@AuthenticationPrincipal CurrentUser current){Map<String,Object> visit=visit(visitId); if(isExecutive(current)&&!current.user().getId().toString().equals(String.valueOf(visit.get("executiveId"))))throw new AccessDeniedException("You cannot update this site visit."); jdbc.update("update site_visits set status=?,feedback=?,rating=?,objections=?,next_action=? where id=?",req.status(),req.feedback(),req.rating(),req.objections(),req.nextAction(),visitId); if("VISITED".equals(req.status()))jdbc.update("update leads set status='VISITED' where id=?",visit.get("leadId")); audit.record(current.user().getId(),"SITE_VISIT",visitId,"UPDATE",visit.toString(),req.status(),null); return visit(visitId);}

  @PostMapping("/leads/{leadId}/negotiations") @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAnyRole('SUPER_ADMIN','SALES_MANAGER','SALES_EXECUTIVE')")
  public Map<String,Object> negotiation(@PathVariable UUID leadId,@Valid @RequestBody NegotiationRequest req,@AuthenticationPrincipal CurrentUser current){leadView(current,leadId); UUID id=UUID.randomUUID(); jdbc.update("insert into negotiations(id,lead_id,unit_id,offered_price,discount_amount,special_offer,competitor,status,requested_by) values (?,?,?,?,?,?,?,?,?)",id,leadId,req.unitId(),req.offeredPrice(),req.discountAmount()==null?BigDecimal.ZERO:req.discountAmount(),req.specialOffer(),req.competitor(),"PENDING",current.user().getId()); jdbc.update("update leads set status='NEGOTIATION' where id=?",leadId); audit.record(current.user().getId(),"NEGOTIATION",id,"CREATE",null,req.offeredPrice().toPlainString(),null); return negotiation(id);}

  @GetMapping("/negotiations") @PreAuthorize("hasAnyRole('SUPER_ADMIN','SALES_MANAGER','SALES_EXECUTIVE')")
  public List<Map<String,Object>> negotiations(@AuthenticationPrincipal CurrentUser current){if(isExecutive(current))return jdbc.queryForList("select n.id,l.lead_number as leadNumber,l.customer_name as customer,n.unit_id as unitId,n.offered_price as offeredPrice,n.discount_amount as discountAmount,n.special_offer as specialOffer,n.status,n.created_at as createdAt from negotiations n join leads l on l.id=n.lead_id where l.assigned_to=? order by n.created_at desc",current.user().getId()); return jdbc.queryForList("select n.id,l.lead_number as leadNumber,l.customer_name as customer,n.unit_id as unitId,n.offered_price as offeredPrice,n.discount_amount as discountAmount,n.special_offer as specialOffer,n.status,n.created_at as createdAt from negotiations n join leads l on l.id=n.lead_id order by n.created_at desc");}

  @PostMapping("/negotiations/{id}/approve") @PreAuthorize("hasAnyRole('SUPER_ADMIN','SALES_MANAGER')")
  public Map<String,Object> approveNegotiation(@PathVariable UUID id,@Valid @RequestBody ApprovalRequest req,@AuthenticationPrincipal CurrentUser current){Map<String,Object> before=negotiation(id); jdbc.update("update negotiations set status=?,approved_by=?,approval_comment=?,updated_at=current_timestamp where id=? and status='PENDING'",req.approve()?"APPROVED":"REJECTED",current.user().getId(),req.comment(),id); audit.record(current.user().getId(),"NEGOTIATION",id,req.approve()?"APPROVE":"REJECT",before.toString(),req.comment(),null); return negotiation(id);}

  @PostMapping("/leads/{leadId}/quotations") @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAnyRole('SUPER_ADMIN','SALES_MANAGER','SALES_EXECUTIVE')")
  public Map<String,Object> quotation(@PathVariable UUID leadId,@Valid @RequestBody QuotationRequest req,@AuthenticationPrincipal CurrentUser current){leadView(current,leadId); Integer version=jdbc.queryForObject("select coalesce(max(version_no),0)+1 from quotation_versions where lead_id=?",Integer.class,leadId); BigDecimal total=req.basePrice().add(n(req.floorRise())).add(n(req.parkingAmount())).add(n(req.gstAmount())).add(n(req.registrationEstimate())).subtract(n(req.discountAmount())); UUID id=UUID.randomUUID(); jdbc.update("insert into quotation_versions(id,lead_id,unit_id,version_no,base_price,floor_rise,parking_amount,gst_amount,registration_estimate,discount_amount,special_offer,total_amount,expires_at,status,created_by) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",id,leadId,req.unitId(),version,req.basePrice(),n(req.floorRise()),n(req.parkingAmount()),n(req.gstAmount()),n(req.registrationEstimate()),n(req.discountAmount()),req.specialOffer(),total,req.expiresAt(),"DRAFT",current.user().getId()); audit.record(current.user().getId(),"QUOTATION",id,"CREATE",null,"version="+version,null); return quotation(id);}

  @GetMapping("/leads/{leadId}/quotations") @PreAuthorize("hasAnyRole('SUPER_ADMIN','SALES_MANAGER','SALES_EXECUTIVE')")
  public List<Map<String,Object>> quotations(@PathVariable UUID leadId,@AuthenticationPrincipal CurrentUser current){leadView(current,leadId); return jdbc.queryForList("select id,lead_id as leadId,unit_id as unitId,version_no as versionNo,base_price as basePrice,floor_rise as floorRise,parking_amount as parkingAmount,gst_amount as gstAmount,registration_estimate as registrationEstimate,discount_amount as discountAmount,special_offer as specialOffer,total_amount as totalAmount,expires_at as expiresAt,status,created_at as createdAt from quotation_versions where lead_id=? order by version_no desc",leadId);}

  @PostMapping("/quotations/{id}/approve") @PreAuthorize("hasAnyRole('SUPER_ADMIN','SALES_MANAGER')")
  public Map<String,Object> approveQuotation(@PathVariable UUID id,@Valid @RequestBody ApprovalRequest req,@AuthenticationPrincipal CurrentUser current){Map<String,Object> before=quotation(id); int changed=jdbc.update("update quotation_versions set status=?,approval_comment=?,approved_by=?,approved_at=case when ? then current_timestamp else null end where id=? and status in ('DRAFT','REVISION')",req.approve()?"APPROVED":"REJECTED",req.comment(),current.user().getId(),req.approve(),id); if(changed==0)throw new ResponseStatusException(HttpStatus.CONFLICT,"Only a draft or revision quotation can be approved."); audit.record(current.user().getId(),"QUOTATION",id,req.approve()?"APPROVE":"REJECT",before.toString(),req.comment(),null); return quotation(id);}

  @PostMapping("/quotations/{id}/revision") @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAnyRole('SUPER_ADMIN','SALES_MANAGER','SALES_EXECUTIVE')")
  public Map<String,Object> reviseQuotation(@PathVariable UUID id,@Valid @RequestBody QuotationRevisionRequest req,@AuthenticationPrincipal CurrentUser current){Map<String,Object> before=quotation(id);UUID leadId=uuid(value(before,"leadId","leadid"));leadView(current,leadId);if("APPROVED".equals(String.valueOf(value(before,"status"))))jdbc.update("update quotation_versions set status='SUPERSEDED' where id=?",id);Integer version=jdbc.queryForObject("select coalesce(max(version_no),0)+1 from quotation_versions where lead_id=?",Integer.class,leadId);BigDecimal base=req.basePrice()!=null?req.basePrice():money(before,"basePrice");BigDecimal floor=req.floorRise()!=null?req.floorRise():money(before,"floorRise");BigDecimal parking=req.parkingAmount()!=null?req.parkingAmount():money(before,"parkingAmount");BigDecimal gst=req.gstAmount()!=null?req.gstAmount():money(before,"gstAmount");BigDecimal registration=req.registrationEstimate()!=null?req.registrationEstimate():money(before,"registrationEstimate");BigDecimal discount=req.discountAmount()!=null?req.discountAmount():money(before,"discountAmount");String offer=req.specialOffer()!=null?req.specialOffer():String.valueOf(value(before,"specialOffer"));BigDecimal total=base.add(floor).add(parking).add(gst).add(registration).subtract(discount);UUID revisionId=UUID.randomUUID();jdbc.update("insert into quotation_versions(id,lead_id,unit_id,version_no,base_price,floor_rise,parking_amount,gst_amount,registration_estimate,discount_amount,special_offer,total_amount,expires_at,status,created_by) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",revisionId,leadId,uuid(value(before,"unitId","unitid")),version,base,floor,parking,gst,registration,discount,offer,total,req.expiresAt()!=null?req.expiresAt():date(value(before,"expiresAt")),"REVISION",current.user().getId());audit.record(current.user().getId(),"QUOTATION",revisionId,"REVISION",before.toString(),"version="+version,null);return quotation(revisionId);}

  @PostMapping("/leads/{leadId}/bookings") @ResponseStatus(HttpStatus.CREATED) @Transactional @PreAuthorize("hasAnyRole('SUPER_ADMIN','SALES_MANAGER','SALES_EXECUTIVE')")
  public Map<String,Object> booking(@PathVariable UUID leadId,@Valid @RequestBody BookingRequest req,@AuthenticationPrincipal CurrentUser current){leadView(current,leadId); Map<String,Object> quote=quotation(req.quotationId()); if(!leadId.toString().equals(String.valueOf(quote.get("leadid")))&&!leadId.toString().equals(String.valueOf(quote.get("leadId"))))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Quotation does not belong to this lead."); if(!"APPROVED".equals(String.valueOf(value(quote,"status"))))throw new ResponseStatusException(HttpStatus.CONFLICT,"Only an approved quotation can be booked."); UUID unitId=uuid(value(quote,"unitid","unitId")); if(unitId==null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"A unit is required for booking."); int changed=jdbc.update("update units set status='BOOKED',reserved_until=null where id=? and status in ('AVAILABLE','RESERVED')",unitId); if(changed==0)throw new ResponseStatusException(HttpStatus.CONFLICT,"This unit is already booked or unavailable."); UUID id=UUID.randomUUID(); String bookingNumber="BK-"+LocalDate.now().getYear()+"-"+UUID.randomUUID().toString().substring(0,8).toUpperCase(); jdbc.update("insert into bookings(id,booking_number,lead_id,unit_id,quotation_id,booking_amount,booking_date,status,confirmed_by,payment_validated) values (?,?,?,?,?,?,CURRENT_DATE,'CONFIRMED',?,true)",id,bookingNumber,leadId,unitId,req.quotationId(),req.bookingAmount(),current.user().getId()); String receipt="RC-"+LocalDate.now().getYear()+"-"+UUID.randomUUID().toString().substring(0,8).toUpperCase(); jdbc.update("insert into customer_payments(booking_id,receipt_number,payment_type,amount,payment_date,payment_mode,transaction_reference,status) values (?,?, 'BOOKING_AMOUNT',?,CURRENT_DATE,?,?, 'PAID')",id,receipt,req.bookingAmount(),req.paymentMode(),req.transactionReference()); jdbc.update("update leads set status='BOOKED' where id=?",leadId); audit.record(current.user().getId(),"BOOKING",id,"CONFIRM",null,bookingNumber,null); return booking(id);}

  @GetMapping("/bookings") @PreAuthorize("hasAnyRole('SUPER_ADMIN','SALES_MANAGER','SALES_EXECUTIVE')")
  public List<Map<String,Object>> bookings(@AuthenticationPrincipal CurrentUser current){if(isExecutive(current))return jdbc.queryForList("select b.id,b.booking_number as bookingNumber,l.lead_number as leadNumber,l.customer_name as customer,u.unit_number as unit,b.booking_amount as bookingAmount,b.booking_date as bookingDate,b.status,b.payment_validated as paymentValidated from bookings b join leads l on l.id=b.lead_id join units u on u.id=b.unit_id where l.assigned_to=? order by b.created_at desc",current.user().getId()); return jdbc.queryForList("select b.id,b.booking_number as bookingNumber,l.lead_number as leadNumber,l.customer_name as customer,u.unit_number as unit,b.booking_amount as bookingAmount,b.booking_date as bookingDate,b.status,b.payment_validated as paymentValidated from bookings b join leads l on l.id=b.lead_id join units u on u.id=b.unit_id order by b.created_at desc");}

  private Map<String,Object> leadView(CurrentUser current,UUID id){Map<String,Object> lead=jdbc.queryForMap("select l.id,l.lead_number as leadNumber,l.customer_name as customer,l.mobile,l.email,l.city,l.budget_min as budgetMin,l.budget_max as budgetMax,l.preferred_configuration as configuration,l.source,l.status,l.temperature,l.qualification_score as qualificationScore,l.loan_required as loanRequired,l.preferred_location as preferredLocation,l.purchase_timeline as purchaseTimeline,l.purchase_purpose as purchasePurpose,l.notes,l.assigned_to as assignedTo from leads l where l.id=? and l.deleted_at is null",id); if(isExecutive(current)&&!current.user().getId().equals(uuid(value(lead,"assignedto","assignedTo"))))throw new AccessDeniedException("You cannot access this lead."); return lead;}
  private Map<String,Object> visit(UUID id){return jdbc.queryForMap("select id,lead_id as leadId,visit_date as date,visit_time as time,executive_id as executiveId,status,pickup_required as pickupRequired,pickup_address as pickupAddress,visitor_count as visitorCount,preferred_unit_id as preferredUnitId,feedback,rating,objections,next_action as nextAction from site_visits where id=?",id);}
  private Map<String,Object> negotiation(UUID id){return jdbc.queryForMap("select id,lead_id as leadId,unit_id as unitId,offered_price as offeredPrice,discount_amount as discountAmount,special_offer as specialOffer,competitor,status,requested_by as requestedBy,approved_by as approvedBy,approval_comment as approvalComment from negotiations where id=?",id);}
  private Map<String,Object> quotation(UUID id){return jdbc.queryForMap("select id,lead_id as leadId,unit_id as unitId,version_no as versionNo,base_price as basePrice,floor_rise as floorRise,parking_amount as parkingAmount,gst_amount as gstAmount,registration_estimate as registrationEstimate,discount_amount as discountAmount,special_offer as specialOffer,total_amount as totalAmount,expires_at as expiresAt,status,approval_comment as approvalComment,approved_by as approvedBy,approved_at as approvedAt,created_by as createdBy from quotation_versions where id=?",id);}
  private Map<String,Object> booking(UUID id){return jdbc.queryForMap("select id,booking_number as bookingNumber,lead_id as leadId,unit_id as unitId,quotation_id as quotationId,booking_amount as bookingAmount,booking_date as bookingDate,status,payment_validated as paymentValidated from bookings where id=?",id);}
  private boolean isExecutive(CurrentUser u){return u.user().getRoles().stream().anyMatch(r->r.getCode()==RoleCode.SALES_EXECUTIVE);}
  private int score(QualificationRequest r){int score=0;if(r.budgetMax()!=null&&r.budgetMax().compareTo(BigDecimal.ZERO)>0)score+=25;if(Boolean.TRUE.equals(r.loanRequired()))score+=10;if(r.configuration()!=null&&!r.configuration().isBlank())score+=15;if(r.purchaseTimeline()!=null&&!r.purchaseTimeline().isBlank())score+=25;if(r.preferredLocation()!=null&&!r.preferredLocation().isBlank())score+=15;if(r.purchasePurpose()!=null&&!r.purchasePurpose().isBlank())score+=10;return Math.min(100,score);}
  private BigDecimal n(BigDecimal n){return n==null?BigDecimal.ZERO:n;}
  private BigDecimal money(Map<String,Object> row,String key){Object value=value(row,key);return value==null?BigDecimal.ZERO:value instanceof BigDecimal b?b:new BigDecimal(value.toString());}
  private LocalDate date(Object value){if(value==null)return null;if(value instanceof LocalDate d)return d;if(value instanceof java.sql.Date d)return d.toLocalDate();return LocalDate.parse(value.toString());}
  private Object value(Map<String,Object> row,String... keys){for(String key:keys){if(row.containsKey(key))return row.get(key);for(String actual:row.keySet())if(actual.equalsIgnoreCase(key))return row.get(actual);}return null;}
  private UUID uuid(Object value){return value==null?null:value instanceof UUID u?u:UUID.fromString(value.toString());}
  public record QualificationRequest(BigDecimal budgetMin,BigDecimal budgetMax,Boolean loanRequired,String preferredLocation,String configuration,String purchaseTimeline,String purchasePurpose,String notes){}
  public record TransferRequest(@NotNull UUID assigneeId,@NotBlank String reason){}
  public record FollowUpRequest(@NotBlank String type,String outcome,String remarks,Instant scheduledAt,Instant nextFollowUpAt,Integer callDurationSeconds,String customerResponse){}
  public record SiteVisitRequest(@NotNull LocalDate date,@NotNull String time,UUID executiveId,Boolean pickupRequired,String pickupAddress,Integer visitorCount,UUID preferredUnitId,String feedback,Integer rating,String objections,String nextAction){}
  public record VisitUpdateRequest(@NotBlank String status,String feedback,Integer rating,String objections,String nextAction){}
  public record NegotiationRequest(@NotNull UUID unitId,@NotNull BigDecimal offeredPrice,BigDecimal discountAmount,String specialOffer,String competitor){}
  public record ApprovalRequest(@NotNull Boolean approve,String comment){}
  public record QuotationRequest(@NotNull UUID unitId,@NotNull BigDecimal basePrice,BigDecimal floorRise,BigDecimal parkingAmount,BigDecimal gstAmount,BigDecimal registrationEstimate,BigDecimal discountAmount,String specialOffer,LocalDate expiresAt){}
  public record QuotationRevisionRequest(BigDecimal basePrice,BigDecimal floorRise,BigDecimal parkingAmount,BigDecimal gstAmount,BigDecimal registrationEstimate,BigDecimal discountAmount,String specialOffer,LocalDate expiresAt){}
  public record BookingRequest(@NotNull UUID quotationId,@NotNull BigDecimal bookingAmount,@NotBlank String paymentMode,String transactionReference){}
}
