package com.saivandan.crm.report;

import com.saivandan.crm.security.AuditService;
import com.saivandan.crm.security.CurrentUser;
import org.springframework.http.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import java.nio.charset.StandardCharsets;
import java.util.*;

@RestController
@RequestMapping("/reports")
public class ReportController {
  private final JdbcTemplate jdbc; private final AuditService audit;
  public ReportController(JdbcTemplate jdbc, AuditService audit){this.jdbc=jdbc;this.audit=audit;}

  @GetMapping("/saved-views") @PreAuthorize("isAuthenticated()")
  public List<Map<String,Object>> savedViews(@AuthenticationPrincipal CurrentUser current){return jdbc.queryForList("select id,report_key as reportKey,view_name as viewName,filters_json as filtersJson,created_at as createdAt,updated_at as updatedAt from report_saved_views where owner_user_id=? order by updated_at desc",current.user().getId());}

  @PostMapping("/saved-views") @PreAuthorize("isAuthenticated()")
  public Map<String,Object> saveView(@Valid @RequestBody SavedViewRequest req,@AuthenticationPrincipal CurrentUser current){UUID id=UUID.randomUUID();jdbc.update("insert into report_saved_views(id,owner_user_id,report_key,view_name,filters_json) values (?,?,?,?,?)",id,current.user().getId(),req.reportKey(),req.viewName(),req.filtersJson());return jdbc.queryForMap("select id,report_key as reportKey,view_name as viewName,filters_json as filtersJson,created_at as createdAt,updated_at as updatedAt from report_saved_views where id=?",id);}

  @GetMapping("/catalog") @PreAuthorize("hasAnyRole('SUPER_ADMIN','SALES_MANAGER','HR','FINANCE','VENDOR','SUPPORT')")
  public List<Map<String,Object>> catalog(@AuthenticationPrincipal CurrentUser current){List<Map<String,Object>> all=List.of(
    Map.of("key","lead-funnel","name","Lead funnel","permission","SALES"),Map.of("key","inventory","name","Unit inventory","permission","INVENTORY"),Map.of("key","collections","name","Collections and receivables","permission","FINANCE"),Map.of("key","vendor-outstanding","name","Vendor outstanding","permission","FINANCE"),Map.of("key","payroll","name","Payroll summary","permission","HR"),Map.of("key","support-sla","name","Support and SLA","permission","SUPPORT"),Map.of("key","project-profit-loss","name","Project profit and loss","permission","FINANCE"));
    Set<String> roles=current.user().getRoles().stream().map(r->r.getCode().name()).collect(java.util.stream.Collectors.toSet()); return all.stream().filter(r->roles.contains("SUPER_ADMIN")||switch(String.valueOf(r.get("permission"))){case "SALES"->roles.contains("SALES_MANAGER");case "INVENTORY"->roles.contains("SALES_MANAGER")||roles.contains("SALES_EXECUTIVE");case "FINANCE"->roles.contains("FINANCE");case "HR"->roles.contains("HR");case "SUPPORT"->roles.contains("SUPPORT");default->false;}).toList();
  }

  @GetMapping("/{key}/data") @PreAuthorize("hasAnyRole('SUPER_ADMIN','SALES_MANAGER','SALES_EXECUTIVE','HR','FINANCE','VENDOR','SUPPORT')")
  public Map<String,Object> data(@PathVariable String key,@RequestParam(required=false) String status,@RequestParam(required=false) String project,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="50") int size,@AuthenticationPrincipal CurrentUser current){assertAllowed(key,current);List<Map<String,Object>> filtered=filter(query(key),status,project);int safePage=Math.max(page,0),safeSize=Math.min(Math.max(size,1),200),from=Math.min(safePage*safeSize,filtered.size()),to=Math.min(from+safeSize,filtered.size());return Map.of("reportKey",key,"generatedAt",java.time.Instant.now(),"rows",filtered.subList(from,to),"rowCount",filtered.size(),"page",safePage,"size",safeSize);}

  @GetMapping("/{key}/export") @PreAuthorize("hasAnyRole('SUPER_ADMIN','SALES_MANAGER','SALES_EXECUTIVE','HR','FINANCE','VENDOR','SUPPORT')")
  public ResponseEntity<byte[]> export(@PathVariable String key,@RequestParam(defaultValue="csv") String format,@RequestParam(required=false) String status,@RequestParam(required=false) String project,@AuthenticationPrincipal CurrentUser current){assertAllowed(key,current);List<Map<String,Object>> rows=filter(query(key),status,project);String normalized=format.toLowerCase(Locale.ROOT);String body;MediaType media;String extension;
    if(normalized.equals("pdf")){body=pdf(rows,key);media=MediaType.APPLICATION_PDF;extension="pdf";}else if(normalized.equals("excel")||normalized.equals("xls")){body=excel(rows,key);media=MediaType.parseMediaType("application/vnd.ms-excel");extension="xls";}else{body=csv(rows);media=MediaType.parseMediaType("text/csv");extension="csv";}
    UUID exportId=UUID.randomUUID();jdbc.update("insert into report_export_audit(id,actor_id,report_key,export_format,row_count) values (?,?,?,?,?)",exportId,current.user().getId(),key,normalized,rows.size());audit.record(current.user().getId(),"REPORT_EXPORT",exportId,"EXPORT",null,key+"/"+normalized,null);return ResponseEntity.ok().contentType(media).header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=\""+key+"."+extension+"\"").body(body.getBytes(StandardCharsets.UTF_8));
  }

  private void assertAllowed(String key,CurrentUser current){if(current.user().getRoles().stream().anyMatch(r->r.getCode().name().equals("SUPER_ADMIN")))return;Set<String> roles=current.user().getRoles().stream().map(r->r.getCode().name()).collect(java.util.stream.Collectors.toSet());boolean allowed=switch(key){case "lead-funnel"->roles.contains("SALES_MANAGER");case "inventory"->roles.contains("SALES_MANAGER")||roles.contains("SALES_EXECUTIVE");case "collections","vendor-outstanding","project-profit-loss"->roles.contains("FINANCE");case "payroll"->roles.contains("HR");case "support-sla"->roles.contains("SUPPORT");default->false;};if(!allowed)throw new org.springframework.web.server.ResponseStatusException(HttpStatus.FORBIDDEN,"You do not have permission to view this report.");}
  public record SavedViewRequest(@NotBlank String reportKey,@NotBlank String viewName,@NotBlank String filtersJson){}

  private List<Map<String,Object>> filter(List<Map<String,Object>> rows,String status,String project){return rows.stream().filter(row->status==null||status.isBlank()||row.values().stream().anyMatch(value->String.valueOf(value).equalsIgnoreCase(status))).filter(row->project==null||project.isBlank()||row.values().stream().anyMatch(value->String.valueOf(value).toLowerCase(Locale.ROOT).contains(project.toLowerCase(Locale.ROOT)))).toList();}

  private List<Map<String,Object>> query(String key){return switch(key){case "lead-funnel"->jdbc.queryForList("select status,count(*) as leadCount from leads group by status order by leadCount desc");case "inventory"->jdbc.queryForList("select status,count(*) as unitCount,coalesce(sum(base_price),0) as value from units group by status order by status");case "collections"->jdbc.queryForList("select payment_date as paymentDate,status,count(*) as receipts,coalesce(sum(amount),0) as amount from customer_payments group by payment_date,status order by payment_date desc");case "vendor-outstanding"->jdbc.queryForList("select v.vendor_name as vendor, count(b.id) as bills, coalesce(sum(b.amount+b.gst_amount-b.paid_amount),0) as outstanding from vendors v left join vendor_bills b on b.vendor_id=v.id and b.status not in ('PAID','FULLY_PAID') group by v.id,v.vendor_name order by outstanding desc");case "payroll"->jdbc.queryForList("select run_month as runMonth,status,count(i.id) as employees,coalesce(sum(i.net_salary),0) as netSalary from payroll_runs r left join payroll_items i on i.payroll_run_id=r.id group by r.id,r.run_month,r.status order by r.run_month desc");case "support-sla"->jdbc.queryForList("select category,status,priority,count(*) as tickets,sum(case when due_at<current_timestamp and status not in ('CLOSED','RESOLVED') then 1 else 0 end) as slaBreaches from support_tickets group by category,status,priority order by slaBreaches desc");case "project-profit-loss"->jdbc.queryForList("select p.code,p.name,coalesce((select sum(cp.amount) from customer_payments cp join bookings b on b.id=cp.booking_id join units u on u.id=b.unit_id where u.project_id=p.id and cp.status='PAID'),0) as revenue,coalesce((select sum(vb.amount+vb.gst_amount) from vendor_bills vb where vb.project_id=p.id),0) as vendorExpense,coalesce((select sum(pc.amount) from petty_cash_entries pc where pc.project_id=p.id and pc.status in ('APPROVED','PAID')),0) as pettyCash from projects p order by p.name");default->throw new org.springframework.web.server.ResponseStatusException(HttpStatus.NOT_FOUND,"Unknown report: "+key);};}
  private String csv(List<Map<String,Object>> rows){if(rows.isEmpty())return "";List<String> cols=new ArrayList<>(rows.get(0).keySet());StringBuilder out=new StringBuilder();out.append(String.join(",",cols)).append('\n');for(Map<String,Object> row:rows){for(int i=0;i<cols.size();i++){if(i>0)out.append(',');String v=String.valueOf(row.getOrDefault(cols.get(i),""));out.append('"').append(v.replace("\"","\"\"")).append('"');}out.append('\n');}return out.toString();}
  private String excel(List<Map<String,Object>> rows,String key){StringBuilder out=new StringBuilder("<html><head><meta charset='utf-8'><title>").append(key).append("</title></head><body><table border='1'><tr>");if(!rows.isEmpty()){for(String c:rows.get(0).keySet())out.append("<th>").append(c).append("</th>");out.append("</tr>");for(Map<String,Object> row:rows){out.append("<tr>");for(Object v:row.values())out.append("<td>").append(String.valueOf(v==null?"":v).replace("&","&amp;").replace("<","&lt;")).append("</td>");out.append("</tr>");}}return out.append("</table></body></html>").toString();}
  private String pdf(List<Map<String,Object>> rows,String key){StringBuilder text=new StringBuilder(key+" report\\nGenerated "+java.time.Instant.now()+"\\n\\n");for(Map<String,Object> row:rows)text.append(row).append("\\n");String escaped=text.toString().replace("\\","\\\\").replace("(","\\(").replace(")","\\)");String stream="BT /F1 9 Tf 36 760 Td ("+escaped.replace("\\n", ") Tj 0 -12 Td (")+") Tj ET";String[] objects={"<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>","<< /Length "+stream.getBytes(StandardCharsets.US_ASCII).length+" >>\\nstream\\n"+stream+"\\nendstream"};StringBuilder pdf=new StringBuilder("%PDF-1.4\\n");List<Integer> offsets=new ArrayList<>();for(int i=0;i<objects.length;i++){offsets.add(pdf.length());pdf.append(i+1).append(" 0 obj\\n").append(objects[i]).append("\\nendobj\\n");}int xref=pdf.length();pdf.append("xref\\n0 ").append(objects.length+1).append("\\n0000000000 65535 f \\n");for(int o:offsets)pdf.append(String.format(Locale.ROOT,"%010d 00000 n \\n",o));pdf.append("trailer\\n<< /Size ").append(objects.length+1).append(" /Root 1 0 R >>\\nstartxref\\n").append(xref).append("\\n%%EOF");return pdf.toString();}
}
