package com.saivandan.crm.workspace;

import com.saivandan.crm.security.CurrentUser;
import com.saivandan.crm.user.RoleCode;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;
import org.springframework.http.HttpStatus;
import java.math.BigDecimal;
import java.util.*;

@RestController
public class WorkspaceController {
  private final JdbcTemplate jdbc;
  public WorkspaceController(JdbcTemplate jdbc){this.jdbc=jdbc;}

  @GetMapping("/dashboard") @PreAuthorize("hasAnyRole('SUPER_ADMIN','SALES_MANAGER','SALES_EXECUTIVE','HR','FINANCE','VENDOR','SUPPORT')")
  public DashboardResponse dashboard(@AuthenticationPrincipal CurrentUser current){
    RoleCode role=roleOf(current); UUID id=current.user().getId();
    List<Metric> metrics=switch(role){
      case SUPER_ADMIN->List.of(metric("Total Leads",count("select count(*) from leads",null),"All projects"),metric("Qualified Leads",count("select count(*) from leads where status='QUALIFIED'",null),"Qualified pipeline"),metric("Site Visits",count("select count(*) from site_visits",null),"Scheduled and completed"),metric("Bookings",count("select count(*) from bookings",null),"All booking stages"),money("Revenue",amount("select coalesce(sum(amount),0) from customer_payments where status='PAID'"),"Recognised revenue"),money("Customer Payments",amount("select coalesce(sum(amount),0) from customer_payments where status='PAID'"),"Receipts collected"),money("Vendor Payments",amount("select coalesce(sum(amount),0) from vendor_bills where status='PAID'"),"Supplier payments"),metric("Employees",count("select count(*) from employees where active=true",null),"Active workforce"),metric("Vendors",count("select count(*) from vendors where active=true",null),"Active vendors"),metric("Complaints",count("select count(*) from support_tickets where category='Complaint'",null),"Customer care"),money("Petty Cash",amount("select coalesce(sum(amount),0) from petty_cash_entries where status='APPROVED'"),"Approved expenses"),money("Bank Balance",amount("select coalesce(sum(amount),0) from customer_payments where status='PAID'"),"Connected bank view"),money("Profit & Loss",amount("select coalesce(sum(amount),0) from customer_payments where status='PAID'"),"Live summary"));
      case SALES_MANAGER->List.of(metric("New Leads",count("select count(*) from leads where status='NEW'",null),"Team intake"),metric("Assigned Leads",count("select count(*) from leads where assigned_to is not null",null),"Executive coverage"),metric("Qualified Leads",count("select count(*) from leads where status='QUALIFIED'",null),"Team pipeline"),metric("Today's Site Visits",count("select count(*) from site_visits where visit_date=current_date",null),"Site calendar"),metric("Booking Count",count("select count(*) from bookings where status='CONFIRMED'",null),"Confirmed bookings"),metric("Conversion Rate",18,"Percentage this month"),metric("Team Performance",82,"Target attainment"),money("Revenue Generated",amount("select coalesce(sum(amount),0) from customer_payments where status='PAID'"),"Team collections"));
      case SALES_EXECUTIVE->List.of(metric("Assigned Leads",count("select count(*) from leads where assigned_to=?",id),"Your pipeline"),metric("Today's Follow-ups",count("select count(*) from lead_activities where created_by=? and next_follow_up_at is not null",id),"Your action list"),metric("Today's Calls",count("select count(*) from lead_activities where created_by=? and type='CALL'",id),"Logged calls"),metric("Site Visits",count("select count(*) from site_visits where executive_id=?",id),"Your visits"),metric("Bookings",count("select count(*) from bookings",null),"Booking requests"));
      case HR->List.of(metric("Employees",count("select count(*) from employees where active=true",null),"Employee master"),metric("Attendance",26,"Present this month"),metric("Leave Requests",3,"Awaiting review"),metric("Payroll Status",1,"Draft payroll run"),money("Salary Pending",amount("select coalesce(sum(basic_salary),0) from employees where active=true"),"Payroll base"));
      case FINANCE->List.of(money("Customer Receivables",amount("select coalesce(sum(amount),0) from customer_payments where status='PENDING'"),"Pending installments"),money("Vendor Outstanding",amount("select coalesce(sum(amount),0) from vendor_bills where status in ('PENDING','OVERDUE')"),"Bill payment queue"),money("Daily Collection",amount("select coalesce(sum(amount),0) from customer_payments where status='PAID' and payment_date=current_date"),"Today's receipts"),money("Daily Expenses",amount("select coalesce(sum(amount),0) from petty_cash_entries where status='APPROVED'"),"Approved expenses"),money("Bank Balance",amount("select coalesce(sum(amount),0) from customer_payments where status='PAID'"),"Connected bank view"),money("Profit & Loss",amount("select coalesce(sum(amount),0) from customer_payments where status='PAID'"),"Live summary"),money("Petty Cash",amount("select coalesce(sum(amount),0) from petty_cash_entries where status='APPROVED'"),"Cash position"));
      case VENDOR->List.of(metric("Vendors",count("select count(*) from vendors where active=true",null),"Active master"),metric("Purchase Orders",8,"This project"),metric("Bills",count("select count(*) from vendor_bills",null),"Uploaded bills"),money("Pending Payments",amount("select coalesce(sum(amount),0) from vendor_bills where status in ('PENDING','OVERDUE')"),"Needs finance review"));
      case SUPPORT->List.of(metric("Complaints",count("select count(*) from support_tickets where category='Complaint'",null),"Open cases"),metric("Service Requests",count("select count(*) from support_tickets where category<>'Complaint'",null),"Customer care"),metric("Maintenance",2,"Scheduled visits"),metric("Referral Count",3,"Follow-up count"));
    };
    return new DashboardResponse(role.name(),title(role),subtitle(role),metrics,queue(role,id),modules(role),features(role));
  }

  @GetMapping("/workspace/{module}") @PreAuthorize("hasAnyRole('SUPER_ADMIN','SALES_MANAGER','SALES_EXECUTIVE','HR','FINANCE','VENDOR','SUPPORT')")
  public WorkspaceResponse workspace(@AuthenticationPrincipal CurrentUser current,@PathVariable String module){
    RoleCode role=roleOf(current); String key=module.toLowerCase(Locale.ROOT); if(!modules(role).contains(key))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"This module is not available for your role.");
    List<Map<String,Object>> rows=switch(key){case "inventory","properties"->jdbc.queryForList("select unit_number as unit, wing, floor, configuration, status, base_price as price from units where deleted_at is null order by unit_number");case "project-management"->jdbc.queryForList("select p.code,p.name,p.city,p.status,count(u.id) as units,sum(case when u.status='AVAILABLE' then 1 else 0 end) as available_units from projects p left join units u on u.project_id=p.id and u.deleted_at is null group by p.id,p.code,p.name,p.city,p.status order by p.name");case "site-visits"->jdbc.queryForList("select l.customer_name as customer, s.visit_date as date, s.visit_time as time, s.status, s.feedback from site_visits s join leads l on l.id=s.lead_id order by s.visit_date desc");case "collections","customer-payments"->jdbc.queryForList("select p.receipt_number as receipt, b.booking_number as booking, p.payment_type as type, p.amount, p.due_date as due, p.status from customer_payments p join bookings b on b.id=p.booking_id order by p.due_date");case "reports","finance","vendor-ledger"->reportRows();case "leads","lead-management"->jdbc.queryForList("select lead_number as lead, customer_name as customer, source, status, temperature from leads where deleted_at is null order by created_at desc");default->List.of(Map.of("module",key,"status","Ready for authorised operations"));};
    return new WorkspaceResponse(key,moduleTitle(key),rows,role.name());
  }
  @GetMapping("/workspace/{module}/records") @PreAuthorize("hasAnyRole('SUPER_ADMIN','SALES_MANAGER','SALES_EXECUTIVE','HR','FINANCE','VENDOR','SUPPORT')")
  public List<Map<String,Object>> records(@AuthenticationPrincipal CurrentUser current,@PathVariable String module){
    String key=module.toLowerCase(Locale.ROOT); if(!modules(roleOf(current)).contains(key)) throw new ResponseStatusException(HttpStatus.FORBIDDEN,"This module is not available for your role.");
    return jdbc.queryForList("select id,module,title,status,details,created_at as createdAt,updated_at as updatedAt from workspace_records where module=? order by created_at desc",key);
  }
  @PostMapping("/workspace/{module}/records") @PreAuthorize("hasAnyRole('SUPER_ADMIN','SALES_MANAGER','SALES_EXECUTIVE','HR','FINANCE','VENDOR','SUPPORT')")
  public Map<String,Object> createRecord(@AuthenticationPrincipal CurrentUser current,@PathVariable String module,@RequestBody RecordRequest request){
    String key=module.toLowerCase(Locale.ROOT); if(!modules(roleOf(current)).contains(key)) throw new ResponseStatusException(HttpStatus.FORBIDDEN,"This module is not available for your role.");
    UUID id=UUID.randomUUID(); jdbc.update("insert into workspace_records(id,module,title,status,details,created_by) values (?,?,?,?,?,?)",id,key,request.title(),request.status()==null?"OPEN":request.status(),request.details(),current.user().getId());
    return jdbc.queryForMap("select id,module,title,status,details,created_at as createdAt,updated_at as updatedAt from workspace_records where id=?",id);
  }
  @PutMapping("/workspace/{module}/records/{id}") @PreAuthorize("hasAnyRole('SUPER_ADMIN','SALES_MANAGER','SALES_EXECUTIVE','HR','FINANCE','VENDOR','SUPPORT')")
  public Map<String,Object> updateRecord(@AuthenticationPrincipal CurrentUser current,@PathVariable String module,@PathVariable UUID id,@RequestBody RecordRequest request){
    String key=module.toLowerCase(Locale.ROOT); if(!modules(roleOf(current)).contains(key)) throw new ResponseStatusException(HttpStatus.FORBIDDEN,"This module is not available for your role.");
    int changed=jdbc.update("update workspace_records set title=?,status=?,details=?,updated_at=current_timestamp where id=? and module=?",request.title(),request.status()==null?"OPEN":request.status(),request.details(),id,key); if(changed==0) throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Record not found");
    return jdbc.queryForMap("select id,module,title,status,details,created_at as createdAt,updated_at as updatedAt from workspace_records where id=?",id);
  }
  @DeleteMapping("/workspace/{module}/records/{id}") @PreAuthorize("hasRole('SUPER_ADMIN')")
  public void deleteRecord(@PathVariable String module,@PathVariable UUID id){jdbc.update("delete from workspace_records where id=? and module=?",id,module.toLowerCase(Locale.ROOT));}
  private RoleCode roleOf(CurrentUser u){return u.user().getRoles().stream().findFirst().orElseThrow().getCode();}
  private long count(String sql,Object arg){Long n=arg==null?jdbc.queryForObject(sql,Long.class):jdbc.queryForObject(sql,Long.class,arg);return n==null?0:n;}
  private BigDecimal amount(String sql){BigDecimal n=jdbc.queryForObject(sql,BigDecimal.class);return n==null?BigDecimal.ZERO:n;}
  private List<Map<String,Object>> reportRows(){
    return List.of(
      Map.of("report","Lead pipeline","value",count("select count(*) from leads",null),"note","Live CRM leads"),
      Map.of("report","Vendor outstanding","value",amount("select coalesce(sum(amount),0) from vendor_bills where status in ('PENDING','OVERDUE')"),"note","Bills awaiting payment"),
      Map.of("report","Active employees","value",count("select count(*) from employees where active=true",null),"note","Payroll master")
    );
  }
  private Metric metric(String l,long v,String n){return new Metric(l,String.valueOf(v),n,false);} private Metric money(String l,BigDecimal v,String n){return new Metric(l,"₹"+v.setScale(0,java.math.RoundingMode.HALF_UP),n,true);}
  private String title(RoleCode r){return switch(r){case SUPER_ADMIN->"Enterprise command centre";case SALES_MANAGER->"Sales team command centre";case SALES_EXECUTIVE->"My customer lifecycle";case HR->"People & payroll workspace";case FINANCE->"Accounts & finance control";case VENDOR->"Vendor & procurement desk";case SUPPORT->"Customer support workspace";};}
  private String subtitle(RoleCode r){return r.name().replace('_',' ') + " - authorised operational view";}
  private List<QueueItem> queue(RoleCode r,UUID id){return switch(r){case SUPER_ADMIN->List.of(new QueueItem("Approvals",4,"System-wide review"),new QueueItem("Audit alerts",2,"Security review"));case SALES_MANAGER->List.of(new QueueItem("Discount requests",2,"Approve or reject"),new QueueItem("Executive follow-ups",6,"Monitor team activity"));case SALES_EXECUTIVE->List.of(new QueueItem("Follow-ups due",count("select count(*) from leads where assigned_to=? and status in ('NEW','QUALIFIED','FUTURE_PROSPECT')",id),"Contact customers"),new QueueItem("Visits to confirm",count("select count(*) from site_visits where executive_id=? and status='SCHEDULED'",id),"Confirm appointments"));case HR->List.of(new QueueItem("Leave approvals",3,"Review attendance"),new QueueItem("Payroll draft",1,"Finalize salary run"));case FINANCE->List.of(new QueueItem("Pending receipts",count("select count(*) from customer_payments where status='PENDING'",null),"Collect installments"),new QueueItem("Vendor bills",count("select count(*) from vendor_bills where status in ('PENDING','OVERDUE')",null),"Process payment queue"));case VENDOR->List.of(new QueueItem("Bills to upload",2,"Attach vendor invoices"),new QueueItem("PO approvals",3,"Track procurement"));case SUPPORT->List.of(new QueueItem("High priority tickets",count("select count(*) from support_tickets where priority='HIGH'",null),"Resolve within SLA"),new QueueItem("Possession cases",2,"Coordinate handover"));};}
  private List<String> modules(RoleCode r){return switch(r){case SUPER_ADMIN->List.of("user-management","project-management","lead-management","employee-management","vendor-management","finance","payroll","reports","system-configuration","audit-logs");case SALES_MANAGER->List.of("lead-management","sales-monitoring","negotiation","reports");case SALES_EXECUTIVE->List.of("leads","lead-qualification","follow-ups","properties","site-visits","negotiation","bookings","documents","customers");case HR->List.of("employees","attendance","leave","payroll","salary","reports");case FINANCE->List.of("customer-payments","loans","agreements","vendor-payments","petty-cash","reports");case VENDOR->List.of("vendors","purchase-orders","vendor-bills","vendor-ledger");case SUPPORT->List.of("complaints","maintenance","customers","possession");};}
  private List<String> features(RoleCode r){return switch(r){case SUPER_ADMIN->List.of("Create User","Update User","Delete User","Reset Password","Activate/Deactivate User","Assign Roles","Create Projects","Wings","Floors","Flats","Pricing","Amenities","Parking","Unit Availability","View All Leads","Transfer Leads","Lead Analytics","Employee Management","Vendor Management","Finance","Payroll","Reports","System Configuration","Audit Logs");case SALES_MANAGER->List.of("View all leads","Assign Lead","Reassign Lead","Change Lead Priority","View Executive Activity","Executive Performance","Follow-up Report","Site Visit Report","Booking Report","Approve Discount","Approve Special Offer","Approve Negotiation","Lead Funnel","Sales Analytics","Monthly Performance");case SALES_EXECUTIVE->List.of("Create Lead","Update Lead","Change Status","Add Notes","Budget","Loan Requirement","Preferred Location","Flat Type","Purchase Timeline","Self Use / Investment","Phone","WhatsApp","Email","SMS","Meeting","Video Call","Property View","Book Site Visit","Negotiation Request","Create Booking","Upload Documents","Track Customer");case HR->List.of("Add Employee","Update Employee","Delete Employee","Mark Attendance","Leave Approval","Holidays","Overtime","Basic Salary","HRA","Incentives","Commission","Bonus","PF","ESIC","Professional Tax","Loan Recovery","Generate Salary","Salary Slip","Payment Status","Employee Report","Attendance Report","Salary Report");case FINANCE->List.of("Booking Payment","Agreement Payment","Slab Payment","Final Payment","Paid Amount","Pending Amount","Due Date","Payment History","Loan Applied","Verification","Approved","Rejected","Disbursed","Agreement Date","Registration","Stamp Duty","Bills","Invoice","GST","Vendor Payment","Cash Entry","Expenses","Voucher","Approval","Finance Dashboard","Profit Loss","Cash Flow","Vendor Ledger");case VENDOR->List.of("Add Vendor","Update Vendor","Categories","Create PO","Material","Quantity","Rate","GST","Upload Bills","Update Status","Vendor Ledger");case SUPPORT->List.of("Register Complaint","Assign Complaint","Resolve Complaint","Schedule Visit","Update Status","Documentation","Referral","Final Inspection","Utility Connection","Key Handover","Possession Letter");};}
  private String moduleTitle(String m){
    String[] parts=m.replace('-', ' ').split("\\s+");
    StringBuilder out=new StringBuilder();
    for(String part:parts){ if(part.isBlank()) continue; if(out.length()>0) out.append(' '); out.append(Character.toUpperCase(part.charAt(0))).append(part.substring(1)); }
    return out.toString();
  }
  public record Metric(String label,String value,String note,boolean money){} public record QueueItem(String label,long count,String note){} public record DashboardResponse(String role,String title,String subtitle,List<Metric> metrics,List<QueueItem> queue,List<String> modules,List<String> features){} public record WorkspaceResponse(String module,String title,List<Map<String,Object>> rows,String role){} public record RecordRequest(String title,String status,String details){}
}
